### ISSUE TITLE
[FEATURE] 원자재 주문관리

### ISSUE THREAD

**Issue by MIdWit0828** [HMDandelion/project1-4-1000-2_back#7]
---
name: 원자재 주문관리
about: 원자재 주문관리 및 거래처 관리에 필요한 restAPI 작성
title: "[FEATURE] "
labels: 기능 개발
assignees: ''

---

**기능 설명**
- [x] 필요 자재량 대비 주문량 조회
- [x] 계획코드로 주문 조회
- [x] 원자재 목록으로 주문 가능한 업체 조회
- [x] 모든 주문 목록 조회
- [x] 주문 상세조회
- [x] 주문 삭제
- [x] 주문 수정/등록
- [x] 전채 공급업체 조회
- [x] 공급업체 목록 삭제
- [x] 공급업체 상세 조회
- [x] 공급업체 등록/수정

**TODO**
- [x] 엔티티 작성
- [x] 기능개발
- [x] 테스트

**기술 사양**
기능 구현에 필요한 기술적 사양이나 고려사항을 명시해주세요.
- 개발중 업데이트 하겠음
